default_platform(:android)

platform :android do
    gradle_properties = {
        "android.injected.signing.store.file" => ENV["KEYSTORE"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
    }

    desc "Build the project"
    lane :build do
        gradle(task: "clean")
        gradle(task: "assemble", build_type: "release", properties: gradle_properties)
        gradle(task: "bundle", build_type: "release", properties: gradle_properties)
    end

    desc "Publish the build to Google Play"
    lane :publish do
        build
        upload_to_play_store(
            track: "production",
            json_key: ENV["PLAY_API_CREDENTIALS"],
            skip_upload_apk: true,
            sync_image_upload: true
        )
    end
end
