name: Build and Release Graviton Player

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build, Sign and Release Graviton Player
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build APK & Bundle
        run: ./gradlew assembleRelease --no-daemon

      - name: Sign APK
        uses: ilharp/sign-android-release@v2
        id: sign
        with:
          signingKey: ${{ secrets.ANDROID_RELEASE_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_RELEASE_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Create changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create changelog summary
        id: changelog-summary
        run: |
          mkdir -p fastlane/metadata/android/en-US/changelogs
          summary_file=$(find fastlane/metadata/android/en-US/changelogs/ -type f | sort -V | tail -n 1)
          if [ -n "$summary_file" ] && [ -f "$summary_file" ]; then
            summary_quoted=$(sed 's/^/> /' "$summary_file")
            summary=$(printf "> [!NOTE]\n> ## Release Highlights\n%s" "$summary_quoted")
          else
            summary="> [!NOTE]\n> Graviton Player Release"
          fi
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo -e "$summary" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Prepare Release Artifacts
        run: |
          mv "${{ steps.sign.outputs.signedFile }}" "GravitonPlayer-${{ github.ref_name }}.apk"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Graviton Player ${{ github.ref_name }}
          body: |
            ${{ steps.changelog-summary.outputs.summary }}

            ${{ steps.changelog.outputs.changes }}
          files: GravitonPlayer-*.apk
          fail_on_unmatched_files: true
          make_latest: true
          
