name: Build and Sign APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build & Sign Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: ilharp/sign-android-release@v2
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: Signed-Release-APK
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          
